version: '2'
services:

#  portainer:
#    container_name: portainer
#    image: portainer/portainer
#    restart: unless-stopped
#    ports:
#      - 9000:9000
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./volumes/portainer/data:/data

  lembrador-contas:
    container_name: lembrador-contas
    image: node:18
    command: bash -c 'npm install && npm run startm'
    working_dir: /root/lembrador-contas
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./volumes/lembrador-contas:/root/lembrador-contas
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    stdin_open: true #docker run -i
    tty: true        #docker run -t
