lembrador-contas:
  container_name: lembrador-contas
  image: lembrador-contas:latest
  build:
    context: ../../volumes/lembrador-contas
    dockerfile: Dockerfile
  command: bun run start
  working_dir: /root/lembrador-contas
  restart: unless-stopped
  env_file:
    - ../../.env
  environment:
    PORT: "9090"
  ports:
    - 3000:9090
    - 9091:9091
  volumes:
    - ../../volumes/lembrador-contas/.credentials:/root/lembrador-contas/.credentials
    - ../../volumes/lembrador-contas/downloads:/root/lembrador-contas/downloads
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"
  stdin_open: true #docker run -i
  tty: true        #docker run -t